import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "nextjs fetch example",
  description: "Generated by create next app",
};

type Time = {
  dateTime: string;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetch(
    "https://timeapi.io/api/Time/current/zone?timeZone=America/New_York",
    {
      cache: "no-store",
    }
  );

  const data: Time = await res.json();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-center">
          <h1 className="text-[30px] font-bold">{data.dateTime}</h1>
        </div>
        {children}
      </body>
    </html>
  );
}
