import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "nextjs fetch example",
  description: "Generated by create next app",
};

type Repository = {
  id: string;
  name: string;
  full_name: string;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetch("https://api.github.com/repos/vercel/next.js");
  const data: Repository = await res.json();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-center">
          <h1 className="text-[30px] font-bold">{data.full_name}</h1>
        </div>
        {children}
      </body>
    </html>
  );
}
